In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


Explain how each term relates to writing data science code

In [2]:
import numpy as np

def distance_python(p1, p2):
    return sum((x-y)**2 for x,y in zip(p1, p2))**0.5

def distance_numpy(p1, p2):
    return np.sqrt(np.sum((np.array(p1) - np.array(p2))**2))

In [4]:
import numpy as np
from numpy import array

# Create an array of integers from 0 to 14
array_result = np.arange(15)
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
import numpy as np
from numpy import ndarray

def create_sequential_array(size: int = 15) -> ndarray:
    """
    Creates a numpy array with sequential integers starting from 0.
    
    Args:
        size (int): The size of the array to create. Default is 15.
        
    Returns:
        ndarray: A numpy array containing integers from 0 to size-1.
        
    Example:
        >>> create_sequential_array(5)
        array([0, 1, 2, 3, 4])
    """
    return np.arange(size)

# Create an array of integers from 0 to 14
array_result = create_sequential_array()
print(array_result)  # Will display: [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
